CREATE TABLE IF NOT EXISTS `cash_handovers` (
  `id` VARCHAR(36) NOT NULL,
  `unitId` VARCHAR(36) NOT NULL,
  `date` DATETIME NOT NULL,
  `totalIncome` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `totalExpense` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `systemBalance` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `cashHanded` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `variance` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `status` ENUM('PENDING','ACCEPTED','REJECTED') NOT NULL DEFAULT 'PENDING',
  `submittedById` VARCHAR(36) NOT NULL,
  `submittedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `acceptedById` VARCHAR(36) DEFAULT NULL,
  `acceptedAt` DATETIME DEFAULT NULL,
  `note` TEXT DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cash_handovers_unit_date_key` (`unitId`, `date`),
  INDEX `cash_handovers_unitId` (`unitId`),
  INDEX `cash_handovers_submittedById` (`submittedById`),
  INDEX `cash_handovers_status` (`status`),
  CONSTRAINT `cash_handovers_ibfk_1` FOREIGN KEY (`unitId`) REFERENCES `units` (`id`) ON UPDATE RESTRICT,
  CONSTRAINT `cash_handovers_ibfk_2` FOREIGN KEY (`submittedById`) REFERENCES `users` (`id`) ON UPDATE RESTRICT,
  CONSTRAINT `cash_handovers_ibfk_3` FOREIGN KEY (`acceptedById`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
